version: 0.2

phases:
  install:
    runtime-version:
      python: 3.8
    comannds:
      # 依存関係をインストール
      - echo Installing dependencies
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      - echo Running tests
      - python3 manage.py test
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
